### ISSUE TITLE
To little space between header and subheader

### ISSUE THREAD

**Issue by leafshore** [Ceerbeerus/beerbolaget-card#3]
Hi, thanks for the card!
In my installation the header with "Beerbolaget" gets to close to "Små partier:...." so the "g" in bolget is on top of the date. 

I updated my copy and added:

`   .release {
                    margin-top: ${this.config.release_date_topmargin};`

and corresponding code in the top as well as update the card configuration to "release_date_topmargin: '-20px'".

That solved my issue, for now. Could you please insert this new option in your code so I can continue with your original code.

Thanks!

**Comment by Ceerbeerus** [comment]
Hi!

I'll add more customization options in next release.

In the meantime you could install card-mod (https://github.com/thomasloven/lovelace-card-mod)
which will fix the problem and enhance your experience by allowing the background color of the header to be changed.

(as I myself use this I totaly forgot about the problem you describe)

**Comment by leafshore** [comment]
Hi, thanks for info and future update!

**Comment by Ceerbeerus** [comment]
If you update to 0.1.51 this is implemented using, "release_date_margin_top".
And will handle to new way the hass config is handled(this card will have broken if you have updated HA to 0.106).
