### ISSUE TITLE
Failed to load in 105.5

### ISSUE THREAD

**Issue by zeputt** [Ceerbeerus/beerbolaget-card#4]
Hi,

I'm not sure if this is related to the #2 issue but I get this error when loading:
![image](https://user-images.githubusercontent.com/9121429/75323921-264a2500-5876-11ea-9394-3878e46b37f7.png)

I haven't changed anything in my config and the relevant passages are as follows:
resources:
  - type: js
    url: /community_plugin/beerbolaget-card/beerbolaget-card.js

(I have it loaded via HACS)

Any ideas?

**Comment by Ceerbeerus** [comment]
Have you had this working before upgrading to .105?

The error suggest your installation cant find the card among your files. Please verify that the card is present in the folder you have specified for the resource.

**Comment by zeputt** [comment]
I have had this working for a long time before the upgrade to .105.5 It worked in previous versions of .105
And yes, the files are present and I have tried both a reinstall and an uninstall and install. All with the same result.

Here you see the file structure:
![image](https://user-images.githubusercontent.com/9121429/75326285-98bd0400-587a-11ea-861b-dd04e6c8f55f.png)
![image](https://user-images.githubusercontent.com/9121429/75326306-a5d9f300-587a-11ea-8fd5-406ed83678c3.png)

**Comment by zeputt** [comment]
This is the only card that stopped working, all others are doing fine...?
I have the following cards enabled:
![image](https://user-images.githubusercontent.com/9121429/75326659-4defbc00-587b-11ea-8987-32c3955a0732.png)

**Comment by Ceerbeerus** [comment]
Try updating to 0.1.51 and tell me how it goes.

**Comment by zeputt** [comment]
0.1.51 did not work, same error as before.
BUT 0.1.53 seems to work like a charm 👍 

Skönt att du hittade felet och det inte var jag som var dum i huvet ;) (Vilket iofs mycket väl kan vara fallet...)

**Comment by zeputt** [comment]
Ahh, wait a minute. With 0.1.53 I don't see if a beer is locally available or not

**Comment by Ceerbeerus** [comment]
Verkar som att HACS ibland kräver att du gör en "reinstall" efter att man uppdaterat. 
Jag fick inte uppdaterade filer när jag provade att updatera men efter en "reinstall" av kortet gick det fint.

ang. lokalt tillgänglig så verkar du ju ha "filter_local" på. dvs. alla som syns är de som finns tillgängliga.

**Comment by zeputt** [comment]
Hmm, just ja. Jag kopierade ju över min config med ditt exempel för att köra helt från början.
Glömde bort att sätta den till false.

**Comment by zeputt** [comment]
Jag tackar så mycket för utomordentlig återkoppling och fixande 🥇 
![image](https://user-images.githubusercontent.com/9121429/75375750-01ce6700-58cf-11ea-9b4c-418d0d7faf12.png)

**Comment by Ceerbeerus** [comment]
Toppen att det löstes! (Y)
